// Base44 client configuration
// This file is auto-generated by Base44

const createEntityClient = (entityName) => ({
  list: async (filters = {}) => {
    const params = new URLSearchParams(filters).toString();
    const res = await fetch(`/api/apps/entities/${entityName}${params ? '?' + params : ''}`);
    if (!res.ok) throw new Error('Failed to fetch');
    return res.json();
  },
  get: async (id) => {
    const res = await fetch(`/api/apps/entities/${entityName}/${id}`);
    if (!res.ok) throw new Error('Failed to fetch');
    return res.json();
  },
  create: async (data) => {
    const res = await fetch(`/api/apps/entities/${entityName}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!res.ok) throw new Error('Failed to create');
    return res.json();
  },
  update: async (id, data) => {
    const res = await fetch(`/api/apps/entities/${entityName}/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!res.ok) throw new Error('Failed to update');
    return res.json();
  },
  delete: async (id) => {
    const res = await fetch(`/api/apps/entities/${entityName}/${id}`, { method: 'DELETE' });
    if (!res.ok) throw new Error('Failed to delete');
    return res.json();
  },
});

export const base44 = {
  entities: {
    Product: createEntityClient('Product'),
    ContactMessage: createEntityClient('ContactMessage'),
  },
};
